all:
  children:
    servers:
      children:
        k8s-hosts:
          vars:
            ansible_user: ubuntu
            ansible_password: ubuntu
            ansible_become: yes
            ansible_become_method: su
            ansible_become_user: root
            ansible_become_password: ubuntu            
          hosts:
            RKM1:
              ansible_host: 192.168.112.10
            RKM2:
              ansible_host: 192.168.112.11
            RKW1:
              ansible_host: 192.168.112.12
            RKW2:
              ansible_host: 192.168.112.13
            RKW3:
              ansible_host: 192.168.112.14
            RKW4:
              ansible_host: 192.168.112.15         