all:
  children:
    servers:
      children:
        k8s-hosts:
          vars:
            ansible_user: ubuntu
            ansible_password: ubuntu
            ansible_become: yes
            ansible_become_method: su
            ansible_become_user: root
            ansible_become_password: ubuntu            
          hosts:
            rkm1:
              ansible_host: 192.168.112.10
            rkm1:
              ansible_host: 192.168.112.11
            rkw1:
              ansible_host: 192.168.112.12
            rkw2:
              ansible_host: 192.168.112.13            