---
- name: Load RKE kernel modules
  hosts: k8s-hosts
  vars:
    kernel_modules:
      - overlay
      - br_netfilter
  tasks:
    - name: Load kernel modules for RKE
      modprobe:
        name: "{{ item }}"
        state: present
      with_items: "{{ kernel_modules }}"
